### ISSUE TITLE
Bot crashes everytime it tries to upload a post

### ISSUE THREAD

**Issue by Axiver** [Garlicvideos/reddits-nightmare#6]
Bot version: 1.2.2
Crash log: 

> (node:6092) UnhandledPromiseRejectionWarning: ParseError: Not possible to parse
API response
    at Request.parseMiddleware (D:\Coding\Projects\nodejs\Unfinished\reddits-nig
htmare\bot\node_modules\instagram-private-api\dist\core\request.js:225:19)
    at Request.errorMiddleware (D:\Coding\Projects\nodejs\Unfinished\reddits-nig
htmare\bot\node_modules\instagram-private-api\dist\core\request.js:229:25)
    at Bluebird.try.catch.err (D:\Coding\Projects\nodejs\Unfinished\reddits-nigh
tmare\bot\node_modules\instagram-private-api\dist\core\request.js:281:22)
    at tryCatcher (D:\Coding\Projects\nodejs\Unfinished\reddits-nightmare\bot\no
de_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Coding\Projects\nodejs\Unfinished\r
eddits-nightmare\bot\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\Coding\Projects\nodejs\Unfinished\reddits-nigh
tmare\bot\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\Coding\Projects\nodejs\Unfinished\reddits-nig
htmare\bot\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Coding\Projects\nodejs\Unfinished\reddits-nig
htmare\bot\node_modules\bluebird\js\release\promise.js:690:18)
    at _drainQueueStep (D:\Coding\Projects\nodejs\Unfinished\reddits-nightmare\b
ot\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\Coding\Projects\nodejs\Unfinished\reddits-nightmare\bot\n
ode_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\Coding\Projects\nodejs\Unfinished\reddits-nightmar
e\bot\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\Coding\Projects\nodejs\
Unfinished\reddits-nightmare\bot\node_modules\bluebird\js\release\async.js:17:14
)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
(node:6092) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)
(node:6092) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

**Comment by Axiver** [comment]
Update: It appears that Instagram has changed their API recently. I will have to rewrite the bot for it to work with the newer versions of Instagram-private-api. Any PRs will be appreciated. It will take me some time to do this.

**Comment by Axiver** [comment]
Hey everyone, I am glad to say that the issue has been fixed. I have re-written pretty much **all** of the code in my free time. However, I will not be putting it up as a release until I finish implementing some new and exciting features.

In order to get your hands on the currently updated, clean, fast and most importantly, working version of the bot, head on over to [the development branch](https://github.com/Garlicvideos/reddits-nightmare/tree/develop) and clone/download the repo.

That version uses the newly updated Instagram API, rendering the bot usable again!
Not only that, your password is no longer stored locally on your system. Although this is a good security measure, I understand that some users may feel that it is inconvenient to input their Instagram password everytime they reboot the bot. As such, this will be optional down the road, by the next release.

Thank you all for continuously supporting this project. I will do my best to push out the next release as soon as I can.
